---
title: "Figure 5"
author: "SK"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    highlight: kate
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
.libPaths(new = "/mnt/nfs/simo/rpack_4_4/")
library(ggplot2)
library(ggforce)
library(patchwork)
library(reshape2)
library(dplyr)
library(DT)
library(cellmig)
library(dunn.test)
library(ggrepel)
dir.create("manuscript_dataset_1")

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r}
o <- get(load("results/cellmig_dataset_1.RData"))
```


# Kruskal-Wallis test + Dunn correction

```{r}
o$posteriors$delta_tp$plate_group <- "p={4,5,6,7,8}"
o$posteriors$delta_tp$plate_group[o$posteriors$delta_tp$plate %in% c("p_1", "p_2", "p_3")] <- "p={1,2,3}"

o$posteriors$delta_t$plate_group <- "p={4,5,6,7,8}"
o$posteriors$delta_t$plate_group[o$posteriors$delta_t$plate %in% c("p_1", "p_2", "p_3")] <- "p={1,2,3}"
o$posteriors$delta_t$plate_group_exp <- "B"
o$posteriors$delta_t$plate_group_exp[o$posteriors$delta_t$plate %in% c("p_1", "p_2", "p_3")] <- "A"
```


```{r}
d <- o$data$proc_x
d$dose <- factor(x = d$dose, levels = c("2.5", "5", "10", "40", "DMSO", "high"))
d$experiment <- "B"
d$experiment[d$plate %in% c("p_1", "p_2", "p_3")] <- "A"
```


# Pool everything

```{r}
q <- d
q <- q[q$dose != "DMSO",]
q$group <- paste0(q$compound, "|", q$dose)

gs_arp <- unique(q$group[q$experiment=="A"])
gs_statin <- unique(q$group[q$experiment=="B"])

dt <- dunn.test(q$v, q$group, method = "bh")
  
dt <- data.frame(p = dt$P, p_adj = dt$P.adjusted, z = dt$Z, contrast = dt$comparisons)
dt$contrast <- gsub(pattern = " ", replacement = '', x = dt$contrast)
dt$group_x <- do.call(rbind, strsplit(x = dt$contrast, split = "\\-"))[,1]
dt$group_y <- do.call(rbind, strsplit(x = dt$contrast, split = "\\-"))[,2]
rm(q)

dt$experiment_x <- ifelse(test = dt$group_x %in% gs_arp, yes = "A", no = "B")
dt$experiment_y <- ifelse(test = dt$group_y %in% gs_arp, yes = "A", no = "B")
dt$mix <- "AB"
dt$mix[dt$experiment_x == "A" & dt$experiment_y == "A"] <- "A"
dt$mix[dt$experiment_x == "B" & dt$experiment_y == "B"] <- "B"
dt$l <- -log10(dt$p_adj)
```


```{r}
u <- get_pairs(x = o, exponentiate = T)
ds <- u$ds

ds$dose <- factor(x = ds$dose, levels = c("2.5", "5", "10", "40", "DMSO", "high"))
ds$compound <- factor(x = ds$compound, levels = c("Fluvastatin", "CK666", 
                                                  "CK869", "Benproperine", "Haloperidol", 
                                                  "DMSO", "Pitavastatin", "Pravastatin"))

ds <- ds[ds$group_x!=ds$group_y,]

srt <- c("Fluvastatin|2.5", "Fluvastatin|5", "Fluvastatin|10",
         "CK666|5", "CK666|10", "CK666|40", 
         "CK869|5", "CK869|10", 
         "Benproperine|5", "Benproperine|10", 
         "Haloperidol|5", "Haloperidol|10", 
         "DMSO|high",
         "Pitavastatin|2.5", "Pitavastatin|5", "Pitavastatin|10",
         "Pravastatin|2.5", "Pravastatin|5", "Pravastatin|10")

ds$group_x <- factor(x = ds$group_x, levels = srt)
ds$group_y <- factor(x = ds$group_y, levels = srt)

ds$group_comparison <- paste0(ds$group_x, '-', ds$group_y)

rm(u, srt)
```

```{r}
w <- merge(x = dt, y = ds, by.x = c("contrast"), by.y = c("group_comparison"), all.x = T)
```

```{r, fig.width=6.5, fig.height=5}
w$mix <- (w$group_x.x %in% gs_arp & w$group_y.x %in% gs_statin)|
  (w$group_y.x %in% gs_arp & w$group_x.x %in% gs_statin)
l <- w
l <- l[duplicated(l$contrast)==F,]

g_A <- ggplot(data = w)+
  geom_point(aes(x = pmax, -log10(p_adj), fill = mix), shape = 21,
             col = "white", alpha = 0.5, size = 1.35, stroke = 0.1)+
  geom_hline(yintercept = 2, linetype = "dashed", col = "black")+
  geom_text_repel(data = l[which(l$pmax > 0.25 & l$pmax < 0.5 & -log10(l$p_adj)>2),],
                  aes(x = pmax, -log10(p_adj), label = contrast, col = mix),
                  size = 2.25, min.segment.length = 0, max.overlaps = 100)+
  geom_text_repel(data = l[which(l$pmax > 0.99 & -log10(l$p_adj)<2),],
                  aes(x = pmax, -log10(p_adj), label = contrast, col = mix),
                  size = 2.25, min.segment.length = 0, max.overlaps = 100)+
  geom_text_repel(data = l[which(l$pmax > 0.5 & l$pmax < 0.75 & -log10(l$p_adj)>2.5),],
                  aes(x = pmax, -log10(p_adj), label = contrast, col = mix),
                  size = 2.25, min.segment.length = 0, max.overlaps = 100)+
  geom_text_repel(data = l[which(l$pmax > 0.5 & l$pmax < 0.95 & -log10(l$p_adj)>4.5),],
                  aes(x = pmax, -log10(p_adj), label = contrast, col = mix),
                  size = 2.25, min.segment.length = 0, max.overlaps = 100)+
  geom_text_repel(data = l[which(l$pmax < 0.9 & -log10(l$p_adj)>9.5),],
                  aes(x = pmax, -log10(p_adj), label = contrast, col = mix),
                  size = 2.25, min.segment.length = 0, max.overlaps = 100)+
  scale_y_log10(name = "-log10(p)")+
  theme_bw(base_size = 10)+
  theme(legend.position = "top")+
  annotation_logticks(base = 10, sides = "l")+
  xlab(label = expression(pi))+
  scale_fill_manual(name = "Cross-experiment", values = c("black", "#ff3232"))+
  scale_color_manual(name = "Cross-experiment", values = c("black", "#ff3232"))


g_B <- ggplot(data = w)+
  geom_errorbarh(aes(y = z, x = rho_M, xmin = rho_L95, 
                    xmax = rho_H95), width = 0, col = "gray")+
  geom_point(aes(y = z, x = rho_M, fill = mix), 
             col = "white", shape = 21, alpha = 0.5, size = 1.35, stroke = 0.1)+
  theme_bw(base_size = 10)+
  theme(legend.position = "top")+
  xlab(label = expression(rho))+
  ylab(label = "z")+
  scale_fill_manual(name = "Cross-experiment", values = c("black", "#ff3232"))+
  scale_color_manual(name = "Cross-experiment", values = c("black", "#ff3232"))
```


```{r, fig.width=6.5, fig.height=3.5}
g_top <- (g_A|g_B)+patchwork::plot_annotation(tag_levels = 'A')
g_top
```


```{r}
ggsave(filename = "manuscript_dataset_1/Figure_5.pdf",
       plot = g_top,
       device = "pdf",
       width = 6.5,
       height = 3.5)
```



```{r}
veryhigh_pval_low_pmax <- c("CK666|5-DMSO|high", "CK869|5-DMSO|high", "DMSO|high-Haloperidol|5", "DMSO|high-Pravastatin|10",
                            "DMSO|high-Pravastatin|10", "DMSO|high-Pravastatin|5", "CK666|10-CK666|5")
high_pval_verylow_pmax <- c("Benproperine|5-Haloperidol|5", "Pravastatin|2.5-Pravastatin|5", "Fluvastatin|2.5-Pitavastatin|2.5")
low_pval_veryhigh_pmax <- c("CK666|40-CK869|10", "Benproperine|10-CK666|40")
```




# Supplementary

```{r}
get_violin_plot <- function(q, pair, delta_pt, delta_p, label, widths = c(1, 2, 1)) {
  
  q <- q[q$dose != "DMSO",]
  q$group <- paste0(q$compound, "|", q$dose)
  q <- q[q$group %in% pair,]
  
  q$plate_group <- "B"
  q$plate_group[q$plate %in% c("p_1", "p_2", "p_3")] <- "A"
  q$plate <- gsub(pattern = "p\\_", replacement = '', x = q$plate)
  
  q$group_x <- "x"
  q$group_x[q$group == pair[1]] <- "x"
  q$group_x[q$group == pair[2]] <- "y"
  
  g1 <- ggplot(data = q)+
    # facet_grid(~group_x, scales = "free_x")+
    geom_sina(aes(x = group_x, y = v), size = 0.2, col = "black")+
    geom_point(data = aggregate(v~group_x, FUN = median, data = q), 
              aes(x = group_x, y = v), 
              fill = "red", shape = 21, size = 1.5, col = "white", stroke = 0.1)+
    theme_bw(base_size = 10)+
    theme(legend.position = "none")+
    theme(strip.text.x = element_text(margin = margin(0.01,0,0.01,0, "cm")))+
    scale_color_grey()+
    scale_y_continuous(breaks = scales::pretty_breaks(3))+
    xlab(label = '')
  
  
  g2 <- ggplot()+
    facet_grid(~group_x, scales = "free_x")+
    geom_sina(data = q, 
              aes(x = plate, y = v, color = plate), size = 0.3)+
    geom_sina(data = aggregate(v~group_x+plate, FUN = median, data = q), 
              aes(x = plate, y = v, color = plate), 
              fill = "salmon", shape = 21, size = 1.5, stroke = 0.1)+
    theme_bw(base_size = 10)+
    theme(strip.text.x = element_text(margin = margin(0.01,0,0.01,0, "cm")))+
    theme(legend.position = "none")+
    scale_color_grey()+
    xlab(label = '')+
    scale_y_continuous(breaks = scales::pretty_breaks(3))+
    ggtitle(label = '', subtitle = paste0(pair[1], " (x) vs. ", pair[2], " (y) ", label))
  
  z <- delta_pt[delta_pt$group %in% pair,]
  z$plate <- gsub(pattern = "p\\_", replacement = '', x = z$plate)
  zt <- delta_p[delta_p$group %in% pair,]
  zt$plate <- gsub(pattern = "p\\_", replacement = '', x = zt$plate)
  
  z$group_x <- "x"
  z$group_x[z$group == pair[1]] <- "x"
  z$group_x[z$group == pair[2]] <- "y"
  
  zt$group_x <- "x"
  zt$group_x[zt$group == pair[1]] <- "x"
  zt$group_x[zt$group == pair[2]] <- "y"
  
  g3 <- ggplot()+
    facet_grid(~group_x, scales = "free_x")+
    geom_point(data = z,
               aes(x = plate, y = exp(mean), col = plate), size = 1)+
    geom_errorbar(data = z,
                  aes(x = plate, y = exp(mean), ymin = exp(X2.5.), 
                      ymax = exp(X97.5.), col = plate), width = 0)+
    geom_point(data = zt,
               aes(x = plate_group_exp, y = exp(mean)), col = "red", size = 1)+
    geom_errorbar(data = zt,
                  aes(x = plate_group_exp, y = exp(mean), ymin = exp(X2.5.), ymax = exp(X97.5.)),
                  width = 0.1, col = "red")+
    theme_bw(base_size = 10)+
    theme(legend.position = "none")+
    theme(strip.text.x = element_text(margin = margin(0.01,0,0.01,0, "cm")))+
    # theme(plot.margin = unit(c(-10,0.1,-10,0.1), "cm"))+
    xlab(label = '')+
    ylab(label = expression(gamma))+
    scale_y_continuous(breaks = scales::pretty_breaks(3))+
    scale_color_grey()

  g <- (g1|g2|g3)+patchwork::plot_layout(widths = widths)
  return(g)
}
```


```{r}
u1 <- l[which(l$contrast %in% veryhigh_pval_low_pmax),]
u1$group <- "-log10(pval)>10 vs. pmax = 0.90-0.95"
u2 <- l[which(l$contrast %in% high_pval_verylow_pmax),]
u2$group <- "-log10(pval)>2 vs. pmax < 0.75"
u3 <- l[which(l$contrast %in% low_pval_veryhigh_pmax),]
u3$group <- "-log10(pval)<2 vs. pmax > 0.99"
u <- rbind(u1, u2, u3)
u$nlp <- -log10(u$p_adj)
u <- u[order(u$nlp, decreasing = T), ]
rm(u1, u2, u3)
```

```{r}
usel <- u
gs_violin <- vector(mode = "list", length = nrow(usel))
for(i in 1:nrow(usel)) {
  gs_violin[[i]] <- get_violin_plot(q = d, 
                                    pair = c(usel$group_x.x[i], usel$group_y.x[i]), 
                                    widths = c(0.3,1.5,1.2),
                                    delta_pt = o$posteriors$delta_tp,
                                    delta_p = o$posteriors$delta_t,
                                    label = '')
}
rm(i)
```

```{r, fig.width=10, fig.height=10}
g <- patchwork::wrap_plots(gs_violin, nrow = 6, ncol = 2, byrow = FALSE)
g
```


```{r}
ggsave(filename = "manuscript_dataset_1/Supplementary_Contradictions.pdf",
       plot = g,
       device = "pdf",
       width = 9,
       height = 9)
```



```{r}
q <- d
q <- q[q$dose != "DMSO",]
q$group <- paste0(q$compound, "|", q$dose)

kt_df <- c()
for(p in unique(q$plate)) {
  kt <- dunn.test(q$v[q$plate == p], q$group[q$plate == p], method = "bh")
  
  kt_df <- rbind(kt_df, data.frame(p = kt$P, p_adj = kt$P.adjusted, z = kt$Z, 
                                   contrast = kt$comparisons, plate = p))
}

kt_df$contrast <- gsub(pattern = " ", replacement = '', x = kt_df$contrast)
kt_df$group_x <- do.call(rbind, strsplit(x = kt_df$contrast, split = "\\-"))[,1]
kt_df$group_y <- do.call(rbind, strsplit(x = kt_df$contrast, split = "\\-"))[,2]
rm(p, kt, q)
```


```{r}
kt_df$experiment_x <- ifelse(test = kt_df$group_x %in% gs_arp, yes = "A", no = "B")
kt_df$experiment_y <- ifelse(test = kt_df$group_y %in% gs_arp, yes = "A", no = "B")
kt_df$mix <- "AB"
kt_df$mix[kt_df$experiment_x == "A" & kt_df$experiment_y == "A"] <- "A"
kt_df$mix[kt_df$experiment_x == "B" & kt_df$experiment_y == "B"] <- "B"
kt_df$l <- -log10(kt_df$p_adj)
kt_df <- kt_df[kt_df$mix != "AB",]
```


```{r, fig.width=9, fig.height=3.5}
g_fdr <- ggplot(data = kt_df)+
  geom_hline(yintercept = 1.3, linetype = "dashed", col = "black")+
  geom_point(aes(x = paste0(group_x, '-', group_y), y = l), alpha = 0.5)+
  geom_point(data = dt[dt$contrast %in% kt_df$contrast,],
             aes(x = paste0(group_x, '-', group_y), y = l), col = "forestgreen", alpha = 0.95, shape = 3, size = 2)+
  theme_bw(base_size = 10)+
  theme(legend.position = "none", 
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  scale_y_log10(name = expression("-log10("*p[FDR]*")"),
                limits = c(min(dt$l, kt_df$l), 220))+
  annotation_logticks(base = 10, sides = "l")+
  xlab(label = '')
```


```{r}
ggsave(filename = "manuscript_dataset_1/Supplementary_FDR.pdf",
       plot = g_fdr,
       device = "pdf",
       width = 8,
       height = 3.5)
```


# Text for manuscript

```{r}
dt <- o$posteriors$delta_t
exp(dt[dt$group == "Haloperidol|5", c("mean", "X2.5.", "X97.5.")])
exp(dt[dt$group == "DMSO|high", c("mean", "X2.5.", "X97.5.")])
get_pairs(x = o, groups = c("Haloperidol|5", "DMSO|high"), exponentiate = T)$ds
```


```{r}
exp(dt[dt$group == "Pravastatin|10", c("mean", "X2.5.", "X97.5.")])
exp(dt[dt$group == "DMSO|high", c("mean", "X2.5.", "X97.5.")])
get_pairs(x = o, groups = c("Pravastatin|10", "DMSO|high"), exponentiate = T)$ds
```

```{r}
exp(dt[dt$group == "Pravastatin|5", c("mean", "X2.5.", "X97.5.")])
exp(dt[dt$group == "DMSO|high", c("mean", "X2.5.", "X97.5.")])
get_pairs(x = o, groups = c("Pravastatin|5", "DMSO|high"), exponentiate = T)$ds
```

