---
title: "Figure 2"
author: "SK"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    highlight: kate
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
.libPaths(new = "/mnt/nfs/simo/rpack_4_4/")
library(ggplot2)
library(ggforce)
library(patchwork)
library(reshape2)
library(dplyr)
library(DT)
library(cellmig)
dir.create("manuscript_dataset_1")

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
o <- get(load("results/cellmig_dataset_1.RData"))
```

# Figure 2

```{r}
o$posteriors$delta_t$dose <- factor(x = o$posteriors$delta_t$dose, 
                                    levels = c("2.5", "5", "10", "40", "DMSO", "high"))
```

```{r, fig.width=7, fig.height=2}
q <- o$posteriors$delta_t
q$compound <- factor(x = q$compound, levels = c("Fluvastatin", "CK666", 
                                                "CK869", "Benproperine", 
                                                "Haloperidol", "DMSO", 
                                                "Pitavastatin", "Pravastatin"))
g1 <- ggplot(data = q)+
    facet_wrap(~compound, nrow = 1, scale = "free_x")+
    geom_hline(yintercept = 1, linetype = "dashed")+
    geom_point(aes(x = dose, y = exp(mean)))+
    geom_errorbar(aes(x = dose, y = exp(mean), ymin = exp(X2.5.), ymax = exp(X97.5.)), width = 0.13)+
    theme_bw(base_size = 10)+
    theme(legend.position = "none")+
    theme(strip.text.x = element_text(margin = margin(0.035,0,0.035,0, "cm")))+
    ylab(label = expression("Overall fold-change ("*delta^"\'"*")"))+
    xlab(label = "Dose")

g1
```

```{r}
ggsave(filename = "manuscript_dataset_1/Figure_2.pdf",
       plot = g1,
       device = "pdf",
       width = 6.5,
       height = 1.75)
```


```{r}
q <- o$posteriors$delta_t
q$mean_exp <- exp(q$mean)
q$L95_exp <- exp(q$X2.5.)
q$H95_exp <- exp(q$X97.5.)
q <- q[,c("compound", "dose", "mean_exp", "L95_exp", "H95_exp")]
```

