---
title: "Figure 7"
author: "SK"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    highlight: kate
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
library(ggplot2)
library(patchwork)
library(cellmig)
dir.create("manuscript_dataset_1")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
# load benchmark data see script src/simulate_cellmig.R
os <- get(load("results/benchmark_B300.RData"))
```

```{r}
# prep data
deltas <- log(c(0.5, 0.6, 0.7, 0.8, 0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 2))
offset <- 6
os$real_delta <- deltas[as.numeric(os$compound)]
os$tp <- (os$real_delta >= os$X2.5. & os$real_delta <= os$X97.5.) & !(os$X2.5.<=0 & os$X97.5.>=0)
os$label <- as.character(exp(os$real_delta))
os$label <- factor(x = os$label, levels = exp(deltas)[-6])

os$N_cells_label <- paste0("N_cells=", os$N_cells)
os$N_cells_label <- factor(x = os$N_cells_label, levels = unique(os$N_cells_label))
os$N_tech_label <- paste0("N_tech=", os$N_tech)
os$N_tech_label <- factor(x = os$N_tech_label, levels = unique(os$N_tech_label))

os$key <- paste0(os$N_bio, '-', os$N_tech, '-', os$N_cells, '-', os$real_delta)
```

# TPR

```{r}
get_boot_tpr <- function(key_fix, os, N, B, key_var) {
  
  get_hdi <- function(vec, hdi_level) {
    # # Taken (and renamed) from "Doing Bayesian Analysis", section 25.2.3 R code 
    # for computing HDI of a MCMC sample
    # Computes highest density interval from a sample of representative values,
    # estimated as shortest credible interval.
    # Arguments:
    # sampleVec
    # is a vector of representative values from a probability distribution.
    # credMass
    # is a scalar between 0 and 1, indicating the mass within the credible
    # interval that is to be estimated.
    # Value:
    # HDIlim is a vector containing the limits of the HDI 
    sortedPts <- sort(vec)
    ciIdxInc <- floor(hdi_level * length(sortedPts))
    nCIs = length(sortedPts) - ciIdxInc
    ciWidth = rep(0 , nCIs)
    for (i in 1:nCIs) {
      ciWidth[i] = sortedPts[i + ciIdxInc] - sortedPts[i]
    }
    HDImin = sortedPts[which.min(ciWidth)]
    HDImax = sortedPts[which.min(ciWidth) + ciIdxInc]
    HDIlim = c(HDImin, HDImax)
    return(HDIlim)
  }
  
  xs <- unique(os[, key_var])
  xs <- xs[order(xs, decreasing = F)]
  
  yhat <- matrix(data = 0, nrow = B, ncol = length(xs))
  for(b in 1:B) {
    for(i in 1:length(xs)) {
      yhat[b,i] <- sum(sample(x = os$tp[os[, "fix"] == key_fix & os[, key_var]==xs[i]], 
                      size = N, replace = TRUE))/N
    }
  }
  
  M <- colMeans(yhat)
  HDI <- apply(X = yhat, MARGIN = 2, FUN = get_hdi, hdi_level = 0.95)
  
  return(data.frame(key_var = key_var, x = xs, key_fix = key_fix, 
                    M = M, L95 = HDI[1,], H95 = HDI[2,]))
}

os$fix <- paste0(os$N_tech, '-', os$N_cells, '-', exp(os$real_delta))

nbio_boot_tpr <- do.call(rbind, parallel::mclapply(mc.cores = 6,
                                               X = unique(os$fix), FUN = get_boot_tpr, os = os, 
                                               N = 100, B = 10^3, key_var = "N_bio"))
nbio_boot_tpr$N_tech <- do.call(rbind, strsplit(x = nbio_boot_tpr$key_fix, split = "-"))[,1]
nbio_boot_tpr$N_cells <- do.call(rbind, strsplit(x = nbio_boot_tpr$key_fix, split = "-"))[,2]
nbio_boot_tpr$delta <- do.call(rbind, strsplit(x = nbio_boot_tpr$key_fix, split = "-"))[,3]
```


```{r}
nbio_boot_tpr$N_cells_label <- paste0("Ncells=", nbio_boot_tpr$N_cells)
nbio_boot_tpr$N_cells_label <- factor(x = nbio_boot_tpr$N_cells_label, levels = unique(nbio_boot_tpr$N_cells_label))
nbio_boot_tpr$N_tech_label <- paste0("Ntech=", nbio_boot_tpr$N_tech)
nbio_boot_tpr$N_tech_label <- factor(x = nbio_boot_tpr$N_tech_label, levels = unique(nbio_boot_tpr$N_tech_label))

g_tpr <- ggplot(data = nbio_boot_tpr)+
  facet_grid(N_cells_label~N_tech_label)+
  geom_hline(yintercept = 80, linetype = "dashed", col = "darkgray")+
  geom_point(aes(x = x, y = M*100, col = delta), size = 1, alpha = 0.5)+
  geom_errorbar(aes(x = x, y = M*100, ymin = L95*100, ymax = H95*100, col = delta), 
                width = 0.1, size = 0.5, alpha = 0.5)+
  geom_line(aes(x = x, y = M*100, col = delta), alpha = 0.5)+
  theme_bw(base_size = 10)+
  theme(strip.text.x = element_text(margin = margin(0.02,0.02,0.02,0.02, "cm")),
        strip.text.y = element_text(margin = margin(0.02,0.02,0.02,0.02, "cm")))+
  xlab(label = expression("N"[bio]))+
  ylab(label = "TPR [%]")+
  scale_color_discrete(name = expression(delta^"'"))+
  scale_x_continuous(breaks = c(3, 6, 9, 12))


g_tpr
```



# W + boot

```{r}
get_boot_w <- function(key_fix, os, N, B, key_var, compute_change) {
  
  get_hdi <- function(vec, hdi_level) {
    # # Taken (and renamed) from "Doing Bayesian Analysis", section 25.2.3 R code 
    # for computing HDI of a MCMC sample
    # Computes highest density interval from a sample of representative values,
    # estimated as shortest credible interval.
    # Arguments:
    # sampleVec
    # is a vector of representative values from a probability distribution.
    # credMass
    # is a scalar between 0 and 1, indicating the mass within the credible
    # interval that is to be estimated.
    # Value:
    # HDIlim is a vector containing the limits of the HDI 
    sortedPts <- sort(vec)
    ciIdxInc <- floor(hdi_level * length(sortedPts))
    nCIs = length(sortedPts) - ciIdxInc
    ciWidth = rep(0 , nCIs)
    for (i in 1:nCIs) {
      ciWidth[i] = sortedPts[i + ciIdxInc] - sortedPts[i]
    }
    HDImin = sortedPts[which.min(ciWidth)]
    HDImax = sortedPts[which.min(ciWidth) + ciIdxInc]
    HDIlim = c(HDImin, HDImax)
    return(HDIlim)
  }
  
  xs <- unique(os[, key_var])
  xs <- xs[order(xs, decreasing = F)]
  
  yhat <- matrix(data = 0, nrow = B, ncol = length(xs))
  for(b in 1:B) {
    for(i in 1:length(xs)) {
      yhat[b,i] <- mean(sample(x = os$W[os[, "fix"] == key_fix & os[, key_var]==xs[i]], 
                      size = N, replace = TRUE))
    }
  }
  
  # return(y)
  M <- colMeans(yhat)
  HDI <- apply(X = yhat, MARGIN = 2, FUN = get_hdi, hdi_level = 0.95)
  
  DM <- numeric(length = ncol(yhat)-1)
  HDI_DM <- matrix(data = 0, nrow = ncol(yhat)-1, ncol = 2)
  if(compute_change) {
    for(i in 2:ncol(yhat)) {
      DM[i-1] <- mean(yhat[,1]/yhat[,i])
      HDI <- get_hdi(vec = yhat[,1]/yhat[,i], hdi_level = 0.95)
      HDI_DM[i-1, 1] <- HDI[1]
      HDI_DM[i-1, 2] <- HDI[2]
    }
    return(data.frame(x = xs[-1], M = DM, L95 = HDI_DM[,1], H95 = HDI_DM[,2], 
               key_fix = key_fix, key_var = key_var))
  }
  
  return(data.frame(key_var = key_var, x = xs, key_fix = key_fix, 
                    M = M, L95 = HDI[1,], H95 = HDI[2,]))
}
```


```{r}
os$fix <- paste0(os$N_tech, '-', os$N_cells)
os$W <- os$X97.5.-os$X2.5.

nbio_boot_w <- do.call(rbind, lapply(X = unique(os$fix), FUN = get_boot_w, os = os, 
                                   N = 100, B = 10^3, key_var = "N_bio",
                                   compute_change = FALSE))
nbio_boot_w$N_tech <- do.call(rbind, strsplit(x = nbio_boot_w$key_fix, split = "-"))[,1]
nbio_boot_w$N_cells <- do.call(rbind, strsplit(x = nbio_boot_w$key_fix, split = "-"))[,2]
```

```{r}
nbio_boot_w$x <- factor(x = nbio_boot_w$x, levels = unique(nbio_boot_w$x))
nbio_boot_w$N_tech_label <- paste0("Ntech=", nbio_boot_w$N_tech)
nbio_boot_w$N_tech_label <- factor(x = nbio_boot_w$N_tech_label, levels = unique(nbio_boot_w$N_tech_label))
nbio_boot_w$N_cells <- factor(x = nbio_boot_w$N_cells, levels = unique(nbio_boot_w$N_cells))

g_w <- ggplot(data = nbio_boot_w)+
  facet_grid(.~N_tech_label)+
  geom_point(aes(x = x, y = M, col = as.factor(N_cells), group = as.factor(N_cells)), 
             size = 1.5, stroke = 0.1,
            position = position_dodge(width = 0.7))+
  geom_errorbar(aes(x = x, y = M, col = as.factor(N_cells), group = as.factor(N_cells), 
                    ymin = L95, ymax = H95), size = 0.5,
                position = position_dodge(width = 0.7), width = 0.2)+
  xlab(label = expression("N"[bio]))+
  ylab(label = "W")+
  theme_bw(base_size = 10)+
  theme(legend.position = "right",
        strip.text.x = element_text(margin = margin(0.02,0.02,0.02,0.02, "cm")),
        strip.text.y = element_text(margin = margin(0.02,0.02,0.02,0.02, "cm")))+
  scale_color_manual(name = expression("N"[cells]), values = c("gray", "#696969", "black"))+
  scale_y_continuous(breaks = scales::pretty_breaks(n=4))
```




```{r, fig.width=6, fig.height=6}
g_main <- (g_w/g_tpr)+patchwork::plot_layout(heights = c(1, 3))+
  patchwork::plot_annotation(tag_levels = "A")
g_main
```


```{r}
ggsave(filename = "manuscript_dataset_1/Figure_7.pdf",
       plot = g_main,
       device = "pdf",
       width = 6,
       height = 5.3)
```


