---
title: "Figure 5CD, sfig 15, sfig 4"
author: "SK"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    highlight: kate
editor_options: 
  markdown: 
    wrap: 72
---

```{r}
require(rstan)
require(ggplot2)
require(ggrepel)
```


```{r}
get_pmax <- function(x) {
  if(all(x==0)) {
    return(0)
  }
  l <- length(x)
  return(2*max(sum(x<0)/l, sum(x>0)/l)-1)
}

get_hdi <- function(vec, hdi_level) {
  sortedPts <- sort(vec)
  ciIdxInc <- floor(hdi_level * length(sortedPts))
  nCIs <- length(sortedPts) - ciIdxInc
  # vapply is preferred for type safety
  ciWidth <- vapply(seq_len(nCIs), function(i) {
    sortedPts[i + ciIdxInc] - sortedPts[i]
  }, numeric(1))
  HDImin <- sortedPts[which.min(ciWidth)]
  HDImax <- sortedPts[which.min(ciWidth) + ciIdxInc]
  HDIlim <- c(HDImin, HDImax)
  return(HDIlim)
}

```


# Get cellmig results from Dataset 1

```{r}
o1 <- get(load(file = "results/cellmig_dataset_1.RData"))
d1 <- o1$data$proc_x
d1$group_id <- d1$group_id+1
o <- d1[duplicated(d1$group_id)==F, "offset"]
```


# Model: simplistic

```{r}
model_code <- "data {
  int<lower=0> N;               // number of cells
  int<lower=0> N_group;         // number groups
  vector[N] y;                  // cell velocity for N cells
  int group_id [N];             // group ID
  int offset [N_group];          // offset = 1 (use for batch correction)
  // priors
  real prior_alpha_p_M;         // prior mean of alpha_p
  real prior_alpha_p_SD;        // prior SD of alpha_p
  real prior_kappa_M;           // prior mean of kappa_mu
  real prior_kappa_SD;          // prior SD of kappa_mu
  real prior_sigma_delta_M;     // prior mean of sigma_delta
  real prior_sigma_delta_SD;    // prior SD of sigma_delta
}

parameters {
  real alpha_p;
  vector <lower=0> [N_group] kappa_exp;
  real <lower=0> sigma_delta;
  vector [N_group] z_1;
  vector [N_group-1] z_4;
}

transformed parameters {
  vector<lower=0> [N_group] mu;
  vector [N_group] mu_exp;
  vector [N_group-1] delta_t;
  vector [N_group] kappa;
  
  delta_t = sigma_delta * z_4;
  for(g in 1:N_group) {
    if(g==1) {
      mu_exp[g] = alpha_p;
    } else {
      mu_exp[g] = alpha_p + delta_t[g-1];
    }
  }
  mu = exp(mu_exp);
  kappa = exp(kappa_exp);
}

model {
  alpha_p ~ normal(prior_alpha_p_M, prior_alpha_p_SD);
  kappa_exp ~ normal(prior_kappa_M, prior_kappa_SD);
  
  // scales
  sigma_delta ~ normal(prior_sigma_delta_M, prior_sigma_delta_SD);
  
  z_1 ~ std_normal();
  z_4 ~ std_normal();

  y ~ gamma(kappa[group_id], kappa[group_id] ./ mu[group_id]);
}

generated quantities {
  real y_hat_sample [N_group];
  real log_lik [N];

  y_hat_sample = gamma_rng(kappa, kappa ./ mu);
  for(i in 1:N) {
    log_lik[i] = gamma_lpdf(y[i] | kappa[group_id[i]], kappa[group_id[i]] ./ mu[group_id[i]]);
  }
}"
```


# Compile simplistic model

```{r}
M_nh <- rstan::stan_model(model_code = model_code)
```

# Fit simplistic model -> save result

```{r}
# Fit simplistic model
fit_nh <- rstan::sampling(object = M_nh,
                          chains = 4, 
                          cores = 4,
                          iter = 2000, 
                          warmup = 1000,
                          data = list(N = d1$N[1],
                                      N_group = max(d1$group_id),
                                      y = d1$v,
                                      group_id = d1$group_id,
                                      offset = o,
                                      prior_alpha_p_M = -0.5,
                                      prior_alpha_p_SD = 1.0,
                                      prior_kappa_M = 1.5,
                                      prior_kappa_SD = 1.0,
                                      prior_sigma_delta_M = 0.0,
                                      prior_sigma_delta_SD = 1.0))
save(fit_nh, file = "manuscript_rebuttal/fit_nh.RData", compress = TRUE)
```


# Load both models: cellmig and simplistic

```{r}
o1 <- get(load("results/cellmig_dataset_1.RData"))
fit_nh <- get(load("manuscript_rebuttal/fit_nh.RData"))
```


# LOOIC based model comparison

```{r}
loo::loo_compare(loo::loo(o1$fit), loo::loo(fit_nh))
```

# Evaluate each LOO

```{r}
rstan::loo(o1$fit)
rstan::loo(fit_nh)
```


# Comparison of delta_t

```{r}
# extract delta_t
dt_nh <- data.frame(summary(fit_nh, par = "delta_t")$summary)
# compute pmax
dt_nh$pmax <- apply(X = extract(fit_nh, par = "delta_t")$delta_t, 
                    MARGIN = 2, FUN = get_pmax)
dt_nh <- dt_nh[,c("mean", "X2.5.", "X97.5.", "pmax")]
colnames(dt_nh) <- paste0(colnames(dt_nh), "_nh")



dt_h <- o1$posteriors$delta_t
dt_h <- dt_h[,c("mean", "X2.5.", "X97.5.", "group", "compound", "dose", "pmax")]
colnames(dt_h) <- paste0(colnames(dt_h), "_h")


# mixed vs non-mixed
q <- o1$data$proc_x
q$experiment <- "B"
q$experiment[q$plate %in% c("p_1", "p_2", "p_3")] <- "A"
q <- q[duplicated(q$group)==F,]

dt <- cbind(dt_h, dt_nh)

dt <- merge(x = dt, y = q[,c("group", "experiment")], 
            by.x = "group_h", by.y = "group", all.x = TRUE)

dt$M_h_exp <- exp(dt$mean_h)
dt$M_nh_exp <- exp(dt$mean_nh)
dt$L_nh_exp <- exp(dt$X2.5._nh)
dt$H_nh_exp <- exp(dt$X97.5._nh)
dt$L_h_exp <- exp(dt$X2.5._h)
dt$H_h_exp <- exp(dt$X97.5._h)

rm(p, pmax, dto, dt_h, dt_nh, q)
```

```{r}
fig_delta_t <- ggplot(data = dt)+
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "black")+
  geom_errorbar(aes(x = M_h_exp, y = M_nh_exp, ymin = L_nh_exp, ymax = H_nh_exp), col = "darkgray")+
  geom_errorbar(aes(x = M_h_exp, y = M_nh_exp, xmin = L_h_exp, xmax = H_h_exp), col = "darkgray")+
  geom_point(aes(x = M_h_exp, y = M_nh_exp, shape = experiment), size = 2)+
  ylab(label = expression("simplistic "*delta[t]*"'"))+
  xlab(label = expression("cellmig "*delta[t]*"'"))+
  theme_bw(base_size = 10)+
  theme(legend.position = c(0.2, 0.8))
```


# Comparison of rho

```{r}
ds_h <- cellmig::get_pairs(x = o1, exponentiate = FALSE)
ds_h <- ds_h$ds[, c("group_x", "group_y", "rho_M", "rho_L95", "rho_H95", "pmax")]
colnames(ds_h)[3:ncol(ds_h)] <- paste0(colnames(ds_h)[3:ncol(ds_h)], "_h")



p <- extract(fit_nh, par = "delta_t")$delta_t
idx <- expand.grid(i = seq_len(ncol(p)), j = seq_len(ncol(p)))
ds_nh <- do.call(rbind, mapply(FUN = function(i, j) {
  d <- p[,i] - p[,j]
  pmax <- get_pmax(d)
  d_M <- mean(d)
  d_HDI <- get_hdi(vec = d, hdi_level = 0.95)
  return(data.frame(group_id_x = i, 
                    group_id_y = j, 
                    rho_M = d_M,
                    rho_L95 = d_HDI[1],
                    rho_H95 = d_HDI[2],
                    rho_M_exp = exp(d_M),
                    rho_L95_exp = exp(d_HDI[1]),
                    rho_H95_exp = exp(d_HDI[2]),
                    pmax = pmax))}, 
  idx$i, idx$j, SIMPLIFY = FALSE))
ds_nh <- ds_nh[, c("rho_M", "rho_L95", "rho_H95", "pmax")]
colnames(ds_nh)[1:ncol(ds_nh)] <- paste0(colnames(ds_nh)[1:ncol(ds_nh)], "_nh")



ds <- cbind(ds_h, ds_nh)

# mixed vs non-mixed
q <- o1$data$proc_x
q$experiment <- "B"
q$experiment[q$plate %in% c("p_1", "p_2", "p_3")] <- "A"
q <- q[q$dose != "DMSO",]
q$group <- paste0(q$compound, "|", q$dose)
gs_arp <- unique(q$group[q$experiment=="A"])
gs_statin <- unique(q$group[q$experiment=="B"])

ds$experiment_x <- ifelse(test = ds$group_x %in% gs_arp, yes = "A", no = "B")
ds$experiment_y <- ifelse(test = ds$group_y %in% gs_arp, yes = "A", no = "B")
ds$mix <- "AB"
ds$mix[ds$experiment_x == "A" & ds$experiment_y == "A"] <- "A"
ds$mix[ds$experiment_x == "B" & ds$experiment_y == "B"] <- "B"
ds$cross_experiment <- ifelse(test = ds$mix == "AB", yes = "yes", no = "no")


ds <- ds[ds$group_x!=ds$group_y,]
ds$key <- apply(X = ds[,c("group_x", "group_y")], MARGIN = 1, FUN = function(x) {
  return(paste0(sort(x), collapse = ","))
})
ds_full <- ds
ds <- ds[duplicated(ds$key)==F,]
```


```{r}
# cleanup
rm(p, pmax, dto, idx, ds1, q, ds_h, ds_nh)
```


```{r}
ds$rho_M_h_exp <- exp(ds$rho_M_h)
ds$rho_L95_h_exp <- exp(ds$rho_L95_h)
ds$rho_H95_h_exp <- exp(ds$rho_H95_h)
ds$rho_M_nh_exp <- exp(ds$rho_M_nh)
ds$rho_L95_nh_exp <- exp(ds$rho_L95_nh)
ds$rho_H95_nh_exp <- exp(ds$rho_H95_nh)

fig_rho <- ggplot(data = ds)+
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "black")+
  geom_errorbar(aes(x = rho_M_h_exp, y = rho_M_nh_exp, 
                    ymin = rho_L95_nh_exp, ymax = rho_H95_nh_exp), col = "darkgray")+
  geom_errorbar(aes(x = rho_M_h_exp, y = rho_M_nh_exp, 
                    xmin = rho_L95_h_exp, xmax = rho_H95_h_exp), col = "darkgray")+
  geom_point(aes(x = rho_M_h_exp, y = rho_M_nh_exp, fill = cross_experiment), 
             shape = 21, col = "white", stroke = 0.001)+
  ylab(label = expression("simplistic "*rho*"'"))+
  xlab(label = expression("cellmig "*rho*"'"))+
  scale_fill_manual(name = "Cross-experiment", 
                    values = c("yes" = "red", "no" = "black"))+
  theme_bw(base_size = 10)+
  theme(legend.position = c(0.2, 0.8))
```


```{r}
table(ds$pmax_h>=0.99,ds$pmax_nh>=0.99)
```



```{r, fig.width=6, fig.height=5.5}
fig5cd <- (fig_delta_t|fig_rho)
```


```{r}
ggsave(filename = "manuscript_rebuttal/Fig_5CD.pdf",
       plot = fig5cd,
       device = "pdf",
       width = 6.25,
       height = 3)
```


# SFig 14

```{r}
ds_full$label <- ifelse(ds_full$pmax_h>=0.99 & ds_full$pmax_nh>=0.99, yes = "both", no = "neither")
ds_full$label[ds_full$pmax_h<0.99 & ds_full$pmax_nh>=0.99] <- "simplified"
srt <- c("Fluvastatin|2.5", "Fluvastatin|5", "Fluvastatin|10",
         "CK666|5", "CK666|10", "CK666|40", 
         "CK869|5", "CK869|10", 
         "Benproperine|5", "Benproperine|10", 
         "Haloperidol|5", "Haloperidol|10", 
         "DMSO|high",
         "Pitavastatin|2.5", "Pitavastatin|5", "Pitavastatin|10",
         "Pravastatin|2.5", "Pravastatin|5", "Pravastatin|10")

ds_full$group_x <- factor(x = ds_full$group_x, levels = srt)
ds_full$group_y <- factor(x = ds_full$group_y, levels = srt)

sfig_simplified_cellmig <- ggplot(data = ds_full)+
  geom_tile(aes(x = group_x, y = group_y, fill = label), col = "white")+
  theme_bw(base_size = 10)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
    scale_fill_manual(name = expression(pi>=0.99), 
                      values = c("both" = "orange", "simplified"="steelblue", "neither" = "black"))+
  xlab(label = "to group")+
  ylab(label = "from group")

ggsave(filename = "manuscript_rebuttal/Supplementary_simplified_cellmig_hits.pdf", 
       plot = sfig_simplified_cellmig,
       device = "pdf",
       width = 6, height = 4.5)
```



# SFig 4

```{r}
d <- get(load("/mnt/nfs/simo/cellmig_application/data/dataset_1.RData"))

o <- cellmig(x = d[,c("well", "plate", "compound", "dose", "v", "offset")],
             control = list(mcmc_warmup = 1000,
                            mcmc_steps = 2000,
                            mcmc_chains = 4,
                            mcmc_cores = 4,
                            mcmc_algorithm = "NUTS",
                            adapt_delta = 0.8,
                            max_treedepth = 10,
                            prior_alpha_p_M = -0.5,
                            prior_alpha_p_SD = 1.0,
                            prior_sigma_bio_M = 0.0,
                            prior_sigma_bio_SD = 1.0,
                            prior_sigma_tech_M = 0.0,
                            prior_sigma_tech_SD = 1.0,
                            prior_kappa_mu_M = 1.5,
                            prior_kappa_mu_SD = 1.0,
                            prior_kappa_sigma_M = 0.0,
                            prior_kappa_sigma_SD = 1.0,
                            prior_sigma_delta_M = 0.0,
                            prior_sigma_delta_SD = 1.0))
save(o, file = "manuscript_rebuttal/fit_o.RData", compress = TRUE)

o_wide <- cellmig(x = d[,c("well", "plate", "compound", "dose", "v", "offset")],
             control = list(mcmc_warmup = 1000,
                            mcmc_steps = 2000,
                            mcmc_chains = 4,
                            mcmc_cores = 4,
                            mcmc_algorithm = "NUTS",
                            adapt_delta = 0.8,
                            max_treedepth = 10,
                            prior_alpha_p_M = -0.5,
                            prior_alpha_p_SD = 3.0,
                            prior_sigma_bio_M = 0.0,
                            prior_sigma_bio_SD = 3.0,
                            prior_sigma_tech_M = 0.0,
                            prior_sigma_tech_SD = 3.0,
                            prior_kappa_mu_M = 1.5,
                            prior_kappa_mu_SD = 3.0,
                            prior_kappa_sigma_M = 0.0,
                            prior_kappa_sigma_SD = 3.0,
                            prior_sigma_delta_M = 0.0,
                            prior_sigma_delta_SD = 3.0))
save(o_wide, file = "manuscript_rebuttal/fit_o_wide.RData", compress = TRUE)
```



```{r}
par_o <- data.frame(summary(o$fit, par = c("delta_t", "delta_tp", "alpha_p", 
                                           "mu", "kappa", "kappa_mu", "kappa_sigma",
                                           "sigma_delta", "sigma_bio", "sigma_tech"))$summary)
par_o$par <- do.call(rbind, strsplit(split = "\\[", x = rownames(par_o)))[,1]

par_o_wide <- data.frame(summary(o_wide$fit, par = c("delta_t", "delta_tp", "alpha_p", 
                                                     "mu", "kappa", "kappa_mu", "kappa_sigma",
                                                     "sigma_delta", "sigma_bio", "sigma_tech"))$summary)
par_o_wide$par <- do.call(rbind, strsplit(split = "\\[", x = rownames(par_o_wide)))[,1]
colnames(par_o_wide) <- paste0(colnames(par_o_wide), "_wide")

pars <- cbind(par_o, par_o_wide)
```


```{r, fig.width=6.5, fig.height=5}
fig_prior_sensitivity_o <- ggplot(data = pars)+
  facet_wrap(~par, ncol = 3, scales = "free")+
  geom_abline(slope = 1, intercept = 0, linetype = "dashed")+
  geom_errorbar(aes(x = mean, y = mean_wide, xmin = X2.5., xmax = X97.5.), col = "darkgray")+
  geom_errorbar(aes(x = mean, y = mean_wide, ymin = X2.5., ymax = X97.5.), col = "darkgray")+
  geom_point(aes(x = mean, y = mean_wide), size = 1, alpha = 0.5)+
  theme_bw(base_size = 10)+
  scale_x_continuous(name = "cellmig model (default priors)", breaks = scales::pretty_breaks(n = 3))+
  scale_y_continuous(name = "cellmig model (wide priors)", breaks = scales::pretty_breaks(n = 3))
```


```{r, fig.width=5, fig.height=8}
fig_prior_sensitivity <- (fig_prior_sensitivity_o/fig_prior_sensitivity_h)+
  patchwork::plot_layout(heights = c(2,1))
```


```{r}
ggsave(filename = "manuscript_rebuttal/Supplementary_prior_sensitivity.pdf",
       plot = fig_prior_sensitivity,
       device = "pdf",
       width = 5,
       height = 8)
```

